Merge with Monero 2-306
graft-project/GraftNetwork pull request #276
Opened 2019-04-08 14:28 UTC by LenyKholodov

2019-04-10 11:04 UTC, EDDragonWolf requested changes

2019-04-10 19:59 UTC, jagerman commented on README.md
> +<<<<<<< HEAD
The readme has multiple overlapping layers of merge conflict markers committed.

2019-04-10 20:01 UTC, jagerman commented on src/version.h.in
>  #define GRAFT_VERSION_TAG "@VERSIONTAG@"
This file should not exist anymore and isn't being used.

2019-04-10 20:04 UTC, jagerman commented on src/cryptonote_config.h
> +  // TODO: subaddress prefix
TODO.

2019-04-10 20:08 UTC, jagerman commented on src/version.cpp.in
> +#define DEF_GRAFT_VERSION_FULL DEF_GRAFT_VERSION "-" DEF_GRAFT_VERSION_TAG
There seems to be no point in having these as definitions.

2019-04-10 20:37 UTC, jagerman commented
This PR is effectively destroying most of the GraftNetwork history by adding a commit that undoes several months of GraftNetwork changes (including deleting whole files) in a single commit then reimports those changes in another commit, bring those files and changes back to life.  As a result `git blame` becomes totally useless before it has fundamentally broken the commit history.

It needs to be properly rebased against master, *not* having master merged into it in history-destroying commits.

2019-04-11 13:24 UTC, jagerman commented on src/version.cpp.in
> +#define DEF_GRAFT_VERSION_FULL DEF_GRAFT_VERSION "-" DEF_GRAFT_VERSION_TAG
(Also they are very wrong values)

2019-04-11 21:19 UTC, LenyKholodov commented
> This PR is effectively destroying most of the GraftNetwork history by adding a commit that undoes several months of GraftNetwork changes (including deleting whole files) in a single commit then reimports those changes in another commit, bring those files and changes back to life. As a result `git blame` becomes totally useless before it has fundamentally broken the commit history.
> 
> It needs to be properly rebased against master, _not_ having master merged into it in history-destroying commits.

This PR won't be merged. This is temporary branch to fix all issues after merge. Actual PR with merge will be done later with changes after this first pass of merging.

2026-01-20 13:21 UTC, closed without merging